### ISSUE TITLE
ERRSTATE 101 Sensors are shorted together after power On

### ISSUE THREAD

**Issue by duchonic** [mattncsu/MTCH112#1]
Hi
I wrote a similar program and i have the same problem with your code.
After powerOn i have the ERRSTATE 0b101 for "Sensors are shorted together".
I can unplug the sensor board and the ERRSTATE dissapears, and the plug in the sensor board and everything works fine.
Any idea

**Comment by mattncsu** [comment]
Sorry for the delay, I wasn't subscribed to notifications on my own library!   Based on the datasheet, I suspect that MTI0 and MTI1 are connected somewhere in your circuit.  I'd examine the sensor board for solder bridges or traces that are connected. Figure 1-2 in the datasheet shows how the circuit should be arranged if you are using MTI1 as a ground channel-note the traces are close but do not touch.

**Comment by duchonic** [comment]
We use the MTCH112 Evaluation Kit with the corresponding proximity sensor board.
[https://www.microchip.com/DevelopmentTools/ProductDetails/PartNo/dm160221](url)
We changed the resistors R1/R2 on the Controllerboard from 4.7kOhm to 270kOhm and it seems that the problem seems to be solved.
